// Copyright 2021 @choko-wallet/request-handler authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@choko-wallet/request-handler', version: '0.1.0' };
